CREATE OR REPLACE VIEW V_NET_OPEN_MARKET AS
SELECT
-- Liquidity providing ops KHR
'LIQ_PROV_KHR' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '175614%' OR BS.BS_GL_NUMBER LIKE '175612%' OR BS.BS_GL_NUMBER LIKE '176614%' OR BS.BS_GL_NUMBER LIKE '176612%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

UNION ALL

--16 Bank Fixed Deposit KHR

SELECT
'BNK_FIX_AC_KHR' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000) * (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '371412%' OR BS.BS_GL_NUMBER LIKE '371413%' OR BS.BS_GL_NUMBER LIKE '372212%'
    OR BS.BS_GL_NUMBER LIKE '372412%' OR BS.BS_GL_NUMBER LIKE '372413 %')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

UNION ALL

--17 Bank NCD KHR
SELECT
'BNK_NCD_KHR' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000) * (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '375712%' OR BS.BS_GL_NUMBER LIKE '375713%' OR BS.BS_GL_NUMBER LIKE '375714%'
    OR BS.BS_GL_NUMBER LIKE '376712%' OR BS.BS_GL_NUMBER LIKE '376713%' OR BS.BS_GL_NUMBER LIKE '376714%' OR BS.BS_GL_NUMBER LIKE '376721%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD));
