CREATE OR REPLACE VIEW V_TOTAL_RESERVED AS
SELECT
--Bank Reserved Account KHR
'BNK_RESV_AC_KHR' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000) * (-1)AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '334513%' OR BS.BS_GL_NUMBER LIKE '334514%' OR BS.BS_GL_NUMBER LIKE '373512%' OR BS.BS_GL_NUMBER LIKE '373513%'
OR BS.BS_GL_NUMBER LIKE '373514%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

UNION

--20 Bank Current Account KHR
SELECT
'BNK_CUR_AC_KHR' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000) * (-1)AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '371212%' OR BS.BS_GL_NUMBER LIKE '371213%' OR BS.BS_GL_NUMBER LIKE '371214%' OR BS.BS_GL_NUMBER LIKE '371215%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

UNION

--21 Bank Settlement Account KHR
SELECT
'BNK_SETL_AC_KHR' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000) * (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '371222000%' OR BS.BS_GL_NUMBER LIKE '371223000%' OR BS.BS_GL_NUMBER LIKE '371224000%' )
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD));
