CREATE OR REPLACE VIEW V_MA_RPT AS
WITH MA_SOURCE AS (
SELECT GLMNT.MTN_MA_ACCOUNT,BS.BS_HOME_AMT, UR.UPLD_RPT_REPORTING_PERIOD,GLMNT.MTN_MA_ACC_MINUS
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
LEFT JOIN LMSAPP.REF_GL_MAINTAIN_MAPPING GLMNT ON BS.BS_GL_NUMBER = GLMNT.MTN_FLEXCUBE_GL_ACCOUNT

UNION ALL
SELECT
'1160000' GLM
,RAT.SCR_EXCH_RATE * RAT.SCR_SDR_HOLDING  * 1000000 AMOUNT
,TRUNC(RAT.SCR_EFECT_DATE) UPLDATE
,''
FROM MA_SOURCE_RATE RAT

UNION ALL
SELECT
'1662100' GLM
,RAT.SCR_EXCH_RATE * RAT.SCR_SDR_HOLDING * (-1) * 1000000 AMOUNT
,TRUNC(RAT.SCR_EFECT_DATE) UPLDATE
,''
FROM MA_SOURCE_RATE RAT

UNION ALL
SELECT
'1662200' GLM
,((RAT.SCR_EXCH_RATE * RAT.SCR_FL_HOLDING) + (RAT.SCR_EXCH_RATE * RAT.SCR_CAPITAL_SDR_ALLOC)) * 1000000 AMOUNT
,TRUNC(TO_DATE(RAT.SCR_EFECT_DATE)) UPLDATE
,''
FROM MA_SOURCE_RATE RAT

UNION ALL
SELECT
'2260000' GLM
,(RAT.SCR_EXCH_RATE * RAT.SCR_FL_HOLDING) * 1000000 AMOUNT
,TRUNC(TO_DATE(RAT.SCR_EFECT_DATE)) UPLDATE
,''
FROM MA_SOURCE_RATE RAT

UNION ALL
SELECT
'2630000' GLM
,(RAT.SCR_EXCH_RATE * RAT.SCR_CAPITAL_SDR_ALLOC) * 1000000 AMOUNT
,TRUNC(TO_DATE(RAT.SCR_EFECT_DATE)) UPLDATE
,''
FROM MA_SOURCE_RATE RAT
)
--END WITH

(
SELECT
('1100000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '11%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL

SELECT
('1110000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '111%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1120000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '112%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1130000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '113%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1140000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '114%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1150000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '115%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1160000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '116%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1200000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '12%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1210000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '121%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1220000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '121%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1230000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '123%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1300000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '13%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1310000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '131%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1320000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '132%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1330000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '133%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1340000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '134%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1400000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '14%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1410000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '141%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1420000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '142%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1430000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '143%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1500000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '15%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1510000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '151%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1511000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '1511%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1512000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '1512%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1520000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '152%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1600000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '16%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1610000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '161%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1620000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '162%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1630000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '163%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1640000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '164%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1650000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '165%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1660000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '166%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1661000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '1661%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1662000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '1662%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1661100') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '16611%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1661200') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '16612%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1662100') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '16621%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1662200') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '16622%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('1000000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '1%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2100000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2110000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '211%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2120000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '212%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2121000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '2121%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2121100') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21211%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2122000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '2122%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2122100') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21221%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2122110') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21221%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2122210') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21222%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD


UNION ALL
SELECT
('2122200') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21222%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2122300') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21223%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2122310') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21223%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2122400') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21224%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2122410') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '21224%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2130000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '213%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2131000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '213%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2140000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '214%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2141000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '214%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2200000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '22%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2260000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '226%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2300000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '23%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2300002') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '23%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2310000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '231%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2400000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '24%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2410000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '241%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2411000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '241%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2420000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '242%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

----O/W: FORIENG CURRENCY of  OTHER IN RESTRICTED DEPOSITS
/*UNION ALL
SELECT
('2421000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '242%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD
*/

UNION ALL
SELECT
('2500000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '25%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2510000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '251%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2600000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '26%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2610000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '261%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2620000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '262%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2630000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '263%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2640000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '264%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2650000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '265%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2700000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '27%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2710000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '271%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2720000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '272%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2730000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '273%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2731000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '273%2'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2000000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '2%'
GROUP BY UPLD_RPT_REPORTING_PERIOD

UNION ALL
SELECT
('2000000') GLM
,SUM(NVL(BS_HOME_AMT,0) * DECODE(MTN_MA_ACC_MINUS,'',1,-1)) * (-1) AMOUNT
,UPLD_RPT_REPORTING_PERIOD  UPLDATE
FROM MA_SOURCE
WHERE MTN_MA_ACCOUNT LIKE '1%'
GROUP BY UPLD_RPT_REPORTING_PERIOD
);
