CREATE OR REPLACE VIEW V_NET_FOREIGN_ASSET AS
SELECT
DESCRIP DESCRIP
,SUM(AMOUNT) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM
  ((SELECT
    'FRN_ASSET' DESCRIP
    ,(NVL(BS.BS_HOME_AMT,0)/1000000) AMOUNT
    ,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
  FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
  WHERE BS.BS_GL_NUMBER LIKE '2212%' OR BS.BS_GL_NUMBER LIKE '1121%' OR BS.BS_GL_NUMBER LIKE '1123%' OR BS.BS_GL_NUMBER LIKE '1124%'
    OR BS.BS_GL_NUMBER LIKE '121211%' OR BS.BS_GL_NUMBER LIKE '121212%' OR BS.BS_GL_NUMBER LIKE '121311%' OR BS.BS_GL_NUMBER LIKE '121312%'
    OR BS.BS_GL_NUMBER LIKE '121411%' OR BS.BS_GL_NUMBER LIKE '121412%' OR BS.BS_GL_NUMBER LIKE '121421%' OR BS.BS_GL_NUMBER LIKE '121422%'
    OR BS.BS_GL_NUMBER LIKE '122212%' OR BS.BS_GL_NUMBER LIKE '122312%' OR BS.BS_GL_NUMBER LIKE '122411%' OR BS.BS_GL_NUMBER LIKE '122212%'
    OR BS.BS_GL_NUMBER LIKE '1223%' OR BS.BS_GL_NUMBER LIKE '1224%' OR BS.BS_GL_NUMBER LIKE '1293%' OR BS.BS_GL_NUMBER LIKE '1412%'
    OR BS.BS_GL_NUMBER LIKE '1414%' OR BS.BS_GL_NUMBER LIKE '1422%' OR BS.BS_GL_NUMBER LIKE '1424%' OR BS.BS_GL_NUMBER LIKE '1493%'
    OR BS.BS_GL_NUMBER LIKE '1491%' OR BS.BS_GL_NUMBER LIKE '1693%' OR BS.BS_GL_NUMBER LIKE '1424%'  OR BS.BS_GL_NUMBER LIKE '1457%'
    OR BS.BS_GL_NUMBER LIKE '1467%'
  )
  union all
  (
  SELECT
    'FRN_ASSET' DESCRIP
    ,(NVL(BS.BS_HOME_AMT,0)/1000000)* (-1) AMOUNT
    ,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
  FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
  where  BS.BS_GL_NUMBER LIKE '329101%' OR BS.BS_GL_NUMBER LIKE '329301%' OR BS.BS_GL_NUMBER LIKE '3493%'
  )

    union all

  ( SELECT
   'FRN_ASSET' DESCRIP
   ,(RAT.SCR_EXCH_RATE * RAT.SCR_SDR_HOLDING) AMOUNT
   ,TRUNC(TO_DATE(RAT.SCR_EFECT_DATE)) UPLDATE
  FROM MA_SOURCE_RATE RAT
  )

  union all

  (SELECT
   'FRN_ASSET' DESCRIP
   ,(RAT.SCR_EXCH_RATE * RAT.SCR_FL_HOLDING) * (-1) AMOUNT
   ,TRUNC(TO_DATE(RAT.SCR_EFECT_DATE)) UPLDATE
  FROM MA_SOURCE_RATE RAT
  )
  )

GROUP BY CAST(UPLDATE AS DATE), DESCRIP

UNION

--3
SELECT
'BNK_RESV_AC_USD' DESCRIP, --Bank Reserved Account
SUM(NVL(BS.BS_HOME_AMT,0)/1000000) * (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '3335%' OR BS.BS_GL_NUMBER LIKE '3345%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

union

--4
SELECT
'BNK_CUR_AC_USD' DESCRIP,--Bank Current Account
SUM(NVL(BS.BS_HOME_AMT,0)/1000000)* (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '331212%' OR BS.BS_GL_NUMBER LIKE '331213%' OR  BS.BS_GL_NUMBER LIKE '331214%' OR BS.BS_GL_NUMBER LIKE '331215%'
     OR BS.BS_GL_NUMBER LIKE '331216%' OR BS.BS_GL_NUMBER LIKE '332212%' OR  BS.BS_GL_NUMBER LIKE '332214%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

union

--5 Bank Settlement Account
SELECT
'BNK_SETL_AC_USD' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000)* (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '331222%' OR BS.BS_GL_NUMBER LIKE '331223%' OR BS.BS_GL_NUMBER LIKE '331224%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

union

--6 Bank Fixed Account
SELECT
'BNK_FIX_AC_USD' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000)* (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '331412%' OR BS.BS_GL_NUMBER LIKE '331413%' OR BS.BS_GL_NUMBER LIKE '331414%' OR BS.BS_GL_NUMBER LIKE '332412%'
      OR BS.BS_GL_NUMBER LIKE '332413%' OR BS.BS_GL_NUMBER LIKE '332414%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

union

--7 NCD Account
SELECT
'BNK_NCD_USD' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000)* (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '335712%' OR BS.BS_GL_NUMBER LIKE '336712%' OR BS.BS_GL_NUMBER LIKE '336713%' OR BS.BS_GL_NUMBER LIKE '336714%'
      OR BS.BS_GL_NUMBER LIKE '335713%' OR BS.BS_GL_NUMBER LIKE '335714%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))

union

--8 Government Deposit
SELECT
'GOV_DEPO_USD' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000)* (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '351211%' OR BS.BS_GL_NUMBER LIKE '351212%' OR BS.BS_GL_NUMBER LIKE '351213%' OR BS.BS_GL_NUMBER LIKE '351214%')
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD))


union

--9 Other Deposit
SELECT
'OTH_DEPO_USD' DESCRIP,
SUM(NVL(BS.BS_HOME_AMT,0)/1000000)* (-1) AMOUNT
,TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD)) UPLDATE
FROM LMSAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LMSAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
WHERE (BS.BS_GL_NUMBER LIKE '353213%' OR BS.BS_GL_NUMBER LIKE '357211%' OR BS.BS_GL_NUMBER LIKE '357212%' OR BS.BS_GL_NUMBER LIKE '357213%'
      OR BS.BS_GL_NUMBER LIKE '357214%' OR BS.BS_GL_NUMBER LIKE '357412%' OR BS.BS_GL_NUMBER LIKE '357414%' --Sight Deposit
      OR BS.BS_GL_NUMBER LIKE '355211%' -- NFPEs Deposit
      OR BS.BS_GL_NUMBER LIKE '335812%' OR BS.BS_GL_NUMBER LIKE '335813%' OR BS.BS_GL_NUMBER LIKE '335814%' OR BS.BS_GL_NUMBER LIKE '335816%'
      OR BS.BS_GL_NUMBER LIKE '336812%' OR BS.BS_GL_NUMBER LIKE '336813%' OR BS.BS_GL_NUMBER LIKE '336814%' --Capital Gurantee Depo
      OR BS.BS_GL_NUMBER LIKE '349404%' OR BS.BS_GL_NUMBER LIKE '341212%' OR BS.BS_GL_NUMBER LIKE '341213%' -- other liabilities
      )
GROUP BY TRUNC(TO_DATE(UR.UPLD_RPT_REPORTING_PERIOD));
