CREATE OR REPLACE VIEW V_LIQ_FOREIGN_ASSET AS
SELECT
'GOLD' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '111%' 
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL
-----------ASS-FOREIGN EXCHANGE----------
SELECT
'FRN_EXC' DESCRIP 
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '112%' 
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL
SELECT
-- Accounts with foreign bank and nonbank Institutions
'AC_W_FRN_INST' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '113%' 
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL
SELECT
-- Other credits to nonresidents
'OTH_CR_NON_RESNT' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '114%' 
GROUP BY CAST(UPLDATE AS DATE)
UNION

------------------------SDR HOLDINGS----------------------
SELECT
'SDR_HOLDING' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '116%' 
GROUP BY CAST(UPLDATE AS DATE)

UNION

SELECT
'LPCO_KHR' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '15%' 
GROUP BY CAST(UPLDATE AS DATE)
;
