CREATE OR REPLACE VIEW V_LIQ_LIQUIDITY_RPT AS
SELECT "UPLDATE","FRN_ASSET","BNK_RESV_AC_USD","BNK_CUR_AC_USD","BNK_SETL_AC_USD","BNK_FIX_AC_USD","BNK_NCD_USD","GOV_DEPO_USD","OTH_DEPO_USD","NET_FRN_ASSET","CCY_CIRCU_KHR","GOV_DEPO_KHR","NET_DOMES_ASSET_KHR","TOTAL_AUTO_FACTOR","LIQ_PROV_KHR","BNK_FIX_AC_KHR","BNK_NCD_KHR","NET_OPEN_MKT_KHR","BNK_RESV_AC_KHR","BNK_CUR_AC_KHR","BNK_SETL_AC_KHR","TOTAL_RESV_KHR","GOLD","FRN_EXC","AC_W_FRN_INST","OTH_CR_NON_RESNT","SDR_HOLDING","LPCO_KHR" FROM
(
SELECT NFA.* from V_LIQ_NET_FOREIGN_ASSET NFA
UNION ALL
SELECT AFA.* FROM V_LIQ_AUTONOMOUS_FACTOR AFA
UNION ALL
SELECT NOM.* FROM V_LIQ_NET_OPEN_MARKET NOM
UNION ALL
SELECT TRE.* FROM V_LIQ_TOTAL_RESERVED TRE
UNION ALL
SELECT FRA.* FROM V_LIQ_FOREIGN_ASSET FRA

UNION ALL
(SELECT
--Total Autonomous Factor
       'TOTAL_AUTO_FACTOR' DESCRIP
       ,SUM(TAF.AMOUNT)
       ,TAF.UPLDATE
FROM V_LIQ_AUTONOMOUS_FACTOR TAF
GROUP BY TAF.UPLDATE)

UNION ALL

(SELECT
--Net Open Market
       'NET_OPEN_MKT_KHR' DESCRIP
       ,SUM(TOM.AMOUNT)
       ,TOM.UPLDATE
FROM V_LIQ_NET_OPEN_MARKET TOM
GROUP BY TOM.UPLDATE)

UNION ALL

(SELECT
--Total Reserved
       'TOTAL_RESV_KHR' DESCRIP
       ,SUM(TOR.AMOUNT)
       ,TOR.UPLDATE
FROM V_LIQ_TOTAL_RESERVED TOR
GROUP BY TOR.UPLDATE)

)
pivot(
sum(NVL(AMOUNT,0)) FOR DESCRIP in (
'FRN_ASSET' FRN_ASSET
,'BNK_RESV_AC_USD' BNK_RESV_AC_USD
,'BNK_CUR_AC_USD' BNK_CUR_AC_USD
,'BNK_SETL_AC_USD' BNK_SETL_AC_USD
,'BNK_FIX_AC_USD' BNK_FIX_AC_USD
,'BNK_NCD_USD' BNK_NCD_USD
,'GOV_DEPO_USD' GOV_DEPO_USD
,'OTH_DEPO_USD' OTH_DEPO_USD
,'NET_FRN_ASSET' NET_FRN_ASSET
,'CCY_CIRCU_KHR' CCY_CIRCU_KHR
,'GOV_DEPO_KHR' GOV_DEPO_KHR
,'NET_DOMES_ASSET_KHR' NET_DOMES_ASSET_KHR
,'TOTAL_AUTO_FACTOR' TOTAL_AUTO_FACTOR
,'LIQ_PROV_KHR' LIQ_PROV_KHR
,'BNK_FIX_AC_KHR' BNK_FIX_AC_KHR
,'BNK_NCD_KHR' BNK_NCD_KHR
,'NET_OPEN_MKT_KHR' NET_OPEN_MKT_KHR
,'BNK_RESV_AC_KHR' BNK_RESV_AC_KHR
,'BNK_CUR_AC_KHR' BNK_CUR_AC_KHR
,'BNK_SETL_AC_KHR' BNK_SETL_AC_KHR
,'TOTAL_RESV_KHR' TOTAL_RESV_KHR
,'GOLD' GOLD
,'FRN_EXC' FRN_EXC
,'AC_W_FRN_INST' AC_W_FRN_INST
,'OTH_CR_NON_RESNT' OTH_CR_NON_RESNT
,'SDR_HOLDING' SDR_HOLDING
,'LPCO_KHR' LPCO_KHR
));
