CREATE OR REPLACE VIEW V_LIQ_MA_RPT AS
WITH MA_SOURCE AS (
SELECT * FROM V_LIQ_MA_SOURCE
)
(SELECT
('1100000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '11%'
GROUP BY UPLDATE

UNION ALL

SELECT
('1110000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '111%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1120000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '112%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1130000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '113%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1140000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '114%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1150000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '115%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1160000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '116%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1200000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '12%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1210000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '121%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1220000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '121%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('1230000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '123%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1300000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '13%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1310000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '131%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1320000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '132%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1330000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '133%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1340000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '134%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1400000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '14%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1410000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '141%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1420000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '142%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1430000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '143%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1500000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '15%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1510000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '151%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1511000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '1511%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1512000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '1512%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1520000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '152%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1600000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '16%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1610000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '161%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1620000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '162%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1630000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '163%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1640000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '164%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1650000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '165%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1660000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '166%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1661000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '1661%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1662000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '1662%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1661100') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '16611%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1661200') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '16612%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1662100') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '16621%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1662200') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '16622%'
GROUP BY UPLDATE

UNION ALL
SELECT
('1000000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '1%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2100000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2110000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '211%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2120000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '212%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2121000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '2121%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2121100') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21211%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2122000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '2122%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2122100') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21221%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2122110') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21221%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('2122210') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21222%2'
GROUP BY UPLDATE


UNION ALL
SELECT
('2122200') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21222%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2122300') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21223%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2122310') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21223%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('2122400') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21224%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2122410') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '21224%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('2130000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '213%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2131000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '213%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('2140000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '214%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2141000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '214%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('2200000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '22%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2260000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '226%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2300000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '23%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2300002') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '23%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('2310000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '231%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2400000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '24%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2410000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '241%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2411000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '241%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('2420000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '242%'
GROUP BY UPLDATE

----O/W: FORIENG CURRENCY of  OTHER IN RESTRICTED DEPOSITS
/*UNION ALL
SELECT
('2421000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '242%2'
GROUP BY UPLDATE
*/

UNION ALL
SELECT
('2500000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '25%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2510000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '251%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2600000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '26%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2610000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '261%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2620000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '262%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2630000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '263%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2640000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '264%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2650000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '265%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2700000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '27%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2710000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '271%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2720000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '272%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2730000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '273%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2731000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '273%2'
GROUP BY UPLDATE

UNION ALL
SELECT
('2000000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '2%'
GROUP BY UPLDATE

UNION ALL
SELECT
('2000000') GLM
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1)) * (-1) AMOUNT
,UPLDATE
FROM MA_SOURCE
WHERE GLM LIKE '1%'
GROUP BY UPLDATE
);
