CREATE OR REPLACE VIEW V_LIQ_NET_OPEN_MARKET AS
SELECT
-- Liquidity providing ops KHR
'LIQ_PROV_KHR' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '15%' --KHR CCY
GROUP BY CAST(UPLDATE AS DATE)
UNION ALL

--16 Bank Fixed Deposit KHR

SELECT
'BNK_FIX_AC_KHR' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '21221%1'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL

--17 Bank NCD KHR
SELECT
'BNK_NCD_KHR' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '21224%1'
GROUP BY CAST(UPLDATE AS DATE);
