CREATE OR REPLACE VIEW V_LIQ_MA_SOURCE_1 AS
SELECT GLMNT.MTN_MA_ACCOUNT GLM
,BS.BS_HOME_AMT AMOUNT
,UR.UPLD_RPT_REPORTING_PERIOD UPLDATE
,GLMNT.MTN_MA_ACC_MINUS AMTMIN
,BS.BS_GL_NUMBER GLAC
FROM LPCOAPP.UPLD_BALANCE_SHEET BS LEFT JOIN LPCOAPP.UPLD_REPORT UR ON BS.BS_REPORT_ID = UR.UPLD_RPT_REPORT_ID
LEFT JOIN LPCOAPP.REF_GL_MAINTAIN_MAPPING GLMNT ON BS.BS_GL_NUMBER = GLMNT.MTN_FLEXCUBE_GL_ACCOUNT

UNION ALL
SELECT
'1160000' GLM
,RAT.SCR_EXCH_RATE * RAT.SCR_SDR_HOLDING  * 1000000 AMOUNT
,TRUNC(RAT.SCR_EFECT_DATE) UPLDATE
,''
,'0' --SDR HOLDINGS
FROM MA_SOURCE_RATE RAT WHERE RAT.SCR_RATE_STATUS = '2'

UNION ALL
SELECT
'1662100' GLM
,RAT.SCR_EXCH_RATE * RAT.SCR_SDR_HOLDING * (-1) * 1000000 AMOUNT
,TRUNC(RAT.SCR_EFECT_DATE) UPLDATE
,''
,'0' --LESS::SDR HOLDINGS
FROM MA_SOURCE_RATE RAT WHERE RAT.SCR_RATE_STATUS = '2'

UNION ALL
SELECT
'1662200' GLM
,((RAT.SCR_EXCH_RATE * RAT.SCR_FL_HOLDING) + (RAT.SCR_EXCH_RATE * RAT.SCR_CAPITAL_SDR_ALLOC)) * 1000000 AMOUNT
,TRUNC(TO_DATE(RAT.SCR_EFECT_DATE)) UPLDATE
,''
,'0' --SDR ALLOCATION
FROM MA_SOURCE_RATE RAT WHERE RAT.SCR_RATE_STATUS = '2'

UNION ALL
SELECT
'2260000' GLM
,(RAT.SCR_EXCH_RATE * RAT.SCR_FL_HOLDING) * 1000000 AMOUNT
,TRUNC(TO_DATE(RAT.SCR_EFECT_DATE)) UPLDATE
,''
,'0' --SDR ALLOCATION NEW
FROM MA_SOURCE_RATE RAT WHERE RAT.SCR_RATE_STATUS = '2'

UNION ALL
SELECT
'2630000' GLM
,(RAT.SCR_EXCH_RATE * RAT.SCR_CAPITAL_SDR_ALLOC) * 1000000 AMOUNT
,TRUNC(TO_DATE(RAT.SCR_EFECT_DATE)) UPLDATE
,''
,'0'--SDR ALLOCATION OLD
FROM MA_SOURCE_RATE RAT WHERE RAT.SCR_RATE_STATUS = '2';
