CREATE OR REPLACE VIEW V_LIQ_NET_FOREIGN_ASSET AS
(
SELECT
'FRN_ASSET' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '11%'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL

SELECT
'FRN_ASSET' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '22%'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL
--3
SELECT
'BNK_RESV_AC_USD' DESCRIP --Bank Reserved Account
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '2121%2'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL

--4--Bank Current Account
SELECT
'BNK_CUR_AC_USD' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '21222%2'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL

--5 Bank Settlement Account
SELECT
'BNK_SETL_AC_USD' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '21223%2'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL

--6 Bank Fixed Account
SELECT
'BNK_FIX_AC_USD' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '21221%2'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL

--7 NCD Account
SELECT
'BNK_NCD_USD' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '21224%2'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL

--8 Government Deposit
SELECT
'GOV_DEPO_USD' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '23%2'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL

--9 Other Deposit
SELECT
'OTH_DEPO_USD' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE
GLM LIKE '213%2' OR GLM LIKE '214%2' OR GLM LIKE '241%2' OR GLM LIKE '273%2'
GROUP BY CAST(UPLDATE AS DATE)
);
