CREATE OR REPLACE VIEW V_LIQ_AUTONOMOUS_FACTOR AS
SELECT
--Net Foreign Asset
'NET_FRN_ASSET' DESCRIP
,SUM(AMOUNT) AMOUNT
,UPLDATE
FROM V_LIQ_NET_FOREIGN_ASSET
GROUP BY UPLDATE

UNION ALL

--11 Currency In Circulation
SELECT
'CCY_CIRCU_KHR' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '211%'
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL
--12 Government Deposit KHR
SELECT
'GOV_DEPO_KHR' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '23%1' --KHR CCY
GROUP BY CAST(UPLDATE AS DATE)

UNION ALL
--13 Net Domestic Asset
SELECT
'NET_DOMES_ASSET_KHR' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) * (-1) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '213%1' OR GLM LIKE '214%1' 
OR GLM LIKE '241%1'OR GLM LIKE '242%' OR GLM LIKE '26%' OR GLM LIKE '27%1' OR GLM LIKE '27%0'
GROUP BY CAST(UPLDATE AS DATE)
UNION ALL

SELECT
'NET_DOMES_ASSET_KHR' DESCRIP
,SUM(NVL(AMOUNT,0) * DECODE(AMTMIN,'',1,-1) /1000000) AMOUNT
,CAST(UPLDATE AS DATE) UPLDATE
FROM V_LIQ_MA_SOURCE
WHERE GLM LIKE '12%' OR GLM LIKE '16%'
GROUP BY CAST(UPLDATE AS DATE)
;
